language: node_js
node_js:
  - "iojs"
  - "8"

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "laukvik"
    token:
      secure: ""
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
