language: node_js
node_js:
  - "iojs"
  - "7"

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "smartflow"
    token:
      secure: ""
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
